# Generated by Django 2.2.7 on 2019-11-20 09:59

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=1000)),
                ('pipeline', models.CharField(max_length=100)),
                ('config', jsonfield.fields.JSONField()),
                ('observation', models.CharField(max_length=100000)),
                ('pipeline_version', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Staging', 'Staging'), ('Transferring', 'Transferring'), ('Waiting', 'Waiting'), ('Running', 'Running'), ('Success', 'Success'), ('Cancelled', 'Cancelled'), ('PermanentFailure', 'PermanentFailure'), ('SystemError', 'SystemError'), ('TemporaryFailure', 'TemporaryFailure')], default='Staging', max_length=20)),
                ('staging', models.CharField(choices=[('new', 'new'), ('scheduled', 'scheduled'), ('inprogress', 'inprogress'), ('completed', 'completed'), ('onhold', 'onhold')], default='new', max_length=20)),
                ('pipeline_response', models.CharField(default='', max_length=1000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('di_fits', models.CharField(default='', max_length=100)),
                ('rw_fits', models.CharField(default='', max_length=100)),
                ('stage_reqid', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
